services:
    data_collector:
        image: ${DOCKER_USERNAME}/lmu-app-backend-data:${ENVIRONMENT}
        build:
            context: .
            dockerfile: docker/Dockerfile-data_collector
            args:
                BUILD_ENV: ${ENVIRONMENT:-development}
                COMMIT_SHA: local
                BUILD_DATE: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
        env_file:
            - .env
        container_name: data_collector
        networks:
            - shared
        environment:
            - PYTHONPATH=/app
            - PYTHONUNBUFFERED=1
            - ENVIRONMENT=${ENVIRONMENT:-development}
        depends_on:
            db:
                condition: service_healthy
        restart: on-failure

    data_collector_dev:
        extends: data_collector
        container_name: data_collector_dev
        volumes:
            - .:/app

networks:
    shared:
        external: true
