FROM python:3.12-slim


WORKDIR /app

# install dependencies
COPY requirements.txt ./
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt

# Only copy data_collector and shared folders
COPY ./data_collector /app/data_collector
COPY ./shared /app/shared


# run data_collector/main.py
CMD ["python", "data_collector/src/main.py"]