from data_fetcher.src.home.models.home_tile_model import (
    HomeTile,
    HomeTileTranslation,
    MovieHomeTile,
)
from shared.src.enums.home_tile_enums import HomeTileEnum
from shared.src.enums.language_enums import LanguageEnum

home_tiles = [
    HomeTile(
        type=HomeTileEnum.TIMELINE,
        size=2,
        translations=[
            HomeTileTranslation(
                language=LanguageEnum.GERMAN,
                title="Timeline",
                description="Timeline",
            ),
            HomeTileTranslation(
                language=LanguageEnum.ENGLISH_US,
                title="Timeline",
                description="Timeline",
            ),
        ],
    ),
    HomeTile(
        type=HomeTileEnum.NEWS,
        size=1,
        translations=[
            HomeTileTranslation(
                language=LanguageEnum.GERMAN,
                title="News",
                description="News",
            ),
            HomeTileTranslation(
                language=LanguageEnum.ENGLISH_US,
                title="News",
                description="News",
            ),
        ],
    ),
    HomeTile(
        type=HomeTileEnum.EVENTS,
        size=1,
        translations=[
            HomeTileTranslation(
                language=LanguageEnum.GERMAN,
                title="Events",
                description="Events",
            ),
            HomeTileTranslation(
                language=LanguageEnum.ENGLISH_US,
                title="Events",
                description="Events",
            ),
        ],
    ),
    HomeTile(
        type=HomeTileEnum.SPORTS,
        size=1,
        translations=[
            HomeTileTranslation(
                language=LanguageEnum.GERMAN,
                title="Sports",
                description="Sports",
            ),
            HomeTileTranslation(
                language=LanguageEnum.ENGLISH_US,
                title="Sports",
                description="Sports",
            ),
        ],
    ),
    HomeTile(
        type=HomeTileEnum.ROOMFINDER,
        size=1,
        translations=[
            HomeTileTranslation(
                language=LanguageEnum.GERMAN,
                title="Roomfinder",
                description="Roomfinder",
            ),
            HomeTileTranslation(
                language=LanguageEnum.ENGLISH_US,
                title="Roomfinder",
                description="Roomfinder",
            ),
        ],
    ),
    HomeTile(
        type=HomeTileEnum.LINKS,
        size=1,
        translations=[
            HomeTileTranslation(
                language=LanguageEnum.GERMAN,
                title="Links",
                description="Links",
            ),
            HomeTileTranslation(
                language=LanguageEnum.ENGLISH_US,
                title="Links",
                description="Links",
            ),
        ],
    ),
    HomeTile(
        type=HomeTileEnum.BENEFITS,
        size=1,
        translations=[
            HomeTileTranslation(
                language=LanguageEnum.GERMAN,
                title="Benefits",
                description="Benefits",
            ),
            HomeTileTranslation(
                language=LanguageEnum.ENGLISH_US,
                title="Benefits",
                description="Benefits",
            ),
        ],
    ),
    MovieHomeTile(
        type=HomeTileEnum.CINEMAS,
        size=3,
    ),
    HomeTile(
        type=HomeTileEnum.WISHLIST,
        size=1,
        translations=[
            HomeTileTranslation(
                language=LanguageEnum.GERMAN,
                title="Wishlist",
                description="Wishlist",
            ),
            HomeTileTranslation(
                language=LanguageEnum.ENGLISH_US,
                title="Wishlist",
                description="Wishlist",
            ),
        ],
    ),
    HomeTile(
        type=HomeTileEnum.FEEDBACK,
        size=1,
        translations=[
            HomeTileTranslation(
                language=LanguageEnum.GERMAN,
                title="Feedback",
                description="Feedback",
            ),
            HomeTileTranslation(
                language=LanguageEnum.ENGLISH_US,
                title="Feedback",
                description="Feedback",
            ),
        ],
    ),
    HomeTile(
        type=HomeTileEnum.LIBRARY,
        size=1,
        translations=[
            HomeTileTranslation(
                language=LanguageEnum.GERMAN,
                title="Feedback",
                description="Feedback",
            ),
            HomeTileTranslation(
                language=LanguageEnum.ENGLISH_US,
                title="Feedback",
                description="Feedback",
            ),
        ],
    ),
]
